#pragma once
#include <vector>
#include "State.hpp"
#include "ProblemData.hpp"

namespace CPOR {

/**
 * @class FFSolver
 * @brief High-performance wrapper for the native C Fast-Forward (FF) Planner.
 * Operates purely on flat bitsets via C-ABI, bypassing all PDDL disk I/O.
 */
class FFSolver {
public:
    /**
     * @brief Executes the FF Relaxed Planning Graph and Enforced Hill Climbing search.
     * @param concrete_state A fully determinized witness state generated by Z3.
     * @param global_problem The problem structure containing domain definitions.
     * @return A vector of Action IDs representing the path to the goal. Empty if failed.
     */
    static std::vector<int> search(const PartiallySpecifiedState& concrete_state, const ProblemDef& global_problem);
};

} // namespace CPOR