(define (problem unix-9)
   (:domain unix)
   (:objects root d0 d1 d2 d0_0 d0_1 d0_2 d1_0 d1_1 d1_2 d2_0 d2_1 d2_2 - DIR my-file - FILE)

   (:init
     (sub-dir root d0)
     (sub-dir root d1)
     (sub-dir root d2)
     (sub-dir d0 d0_0)
     (sub-dir d0 d0_1)
     (sub-dir d0 d0_2)
     (sub-dir d1 d1_0)
     (sub-dir d1 d1_1)
     (sub-dir d1 d1_2)
     (sub-dir d2 d2_0)
     (sub-dir d2 d2_1)
     (sub-dir d2 d2_2)
     (is-cur-dir root)
     (unknown (file-in-dir my-file d0_0))
     (unknown (file-in-dir my-file d0_1))
     (unknown (file-in-dir my-file d0_2))
     (unknown (file-in-dir my-file d1_0))
     (unknown (file-in-dir my-file d1_1))
     (unknown (file-in-dir my-file d1_2))
     (unknown (file-in-dir my-file d2_0))
     (unknown (file-in-dir my-file d2_1))
     (unknown (file-in-dir my-file d2_2))
     (oneof
        (file-in-dir my-file d0_0)
        (file-in-dir my-file d0_1)
        (file-in-dir my-file d0_2)
        (file-in-dir my-file d1_0)
        (file-in-dir my-file d1_1)
        (file-in-dir my-file d1_2)
        (file-in-dir my-file d2_0)
        (file-in-dir my-file d2_1)
        (file-in-dir my-file d2_2)
     )
     )
   (:goal (file-in-dir my-file root))
)
